from .shapes import DrawShape

class DrawLetter(DrawShape): # pylint: disable=too-many-public-methods
    def a(self, r, delta) -> None:
        ...

    def b(self, r, delta) -> None:
        ...

    def c(self, r, delta) -> None:
        ...

    def d(self, r, delta) -> None:
        ...

    def e(self, r, delta) -> None:
        ...

    def f(self, r, delta) -> None:
        ...

    def g(self, r, delta) -> None:
        ...

    def h(self, r, delta) -> None:
        ...

    def i(self, r, delta) -> None:
        self.spoke(r, 20, delta)

    def j(self, r, delta) -> None:
        ...

    def k(self, r, delta) -> None:
        ...

    def l(self, r, delta) -> None:  # noqa: E743
        ...

    def m(self, r, delta) -> None:
        ...

    def n(self, r, delta) -> None:
        ...

    def o(self, r, delta) -> None:
        ...

    def p(self, r, delta) -> None:
        ...

    def q(self, r, delta) -> None:
        ...

    def r(self, r, delta) -> None:
        ...

    def s(self, r, delta) -> None:
        ...

    def t(self, r, delta) -> None:
        ...

    def u(self, r, delta) -> None:
        ...

    def v(self, r, delta) -> None:
        ...

    def w(self, r, delta) -> None:
        ...

    def x(self, r, delta) -> None:
        ...

    def y(self, r, delta) -> None:
        ...

    def z(self, r, delta) -> None:
        ...

    def ea(self, r, delta) -> None:
        ...

    def apostrophe(self, r, delta) -> None:
        ...

    def oa(self, r, delta) -> None:
        ...

    def oi(self, r, delta) -> None:
        ...

    def ou(self, r, delta) -> None:
        ...

    def ch(self, r, delta) -> None:
        ...

    def sh(self, r, delta) -> None:
        ...

    def th(self, r, delta) -> None:
        ...

    def zh(self, r, delta) -> None:
        ...
